"""
08b_extraction_accuracy_presentation.py
=======================================
Build a presentation-ready summary of the NUST extraction accuracy data
(from analysis/data/extraction_accuracy_per_year.csv, generated by
analysis/08_extraction_accuracy.py).

Outputs (analysis/data/):
  extraction_accuracy_presentation.md   -- slide-friendly markdown
  extraction_accuracy_by_decade.csv     -- decade roll-up (5 rows)
  extraction_accuracy_by_decade.png     -- bar chart: % accuracy / decade
"""
import sys
from pathlib import Path
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO = Path(r"C:\Users\vramasub\Desktop\UMN_GIT\NUST_Data_Prep")
SRC = REPO / "analysis" / "data" / "_shared" / "extraction_accuracy_per_year.csv"
OUT_DIR = REPO / "analysis" / "data" / "_shared"


def decade_label(year: int) -> str:
    d = (year // 10) * 10
    return f"{d}s"


def main():
    if not SRC.exists():
        sys.exit(f"ERROR: missing {SRC}. Run analysis/08_extraction_accuracy.py first.")
    df = pd.read_csv(SRC)
    df["year"] = df["year"].astype(int)
    df["decade"] = df["year"].apply(decade_label)

    # --- Decade roll-up -----------------------------------------------------
    grp = df.groupby("decade", sort=True)
    decade_df = pd.DataFrame({
        "years_n": grp["year"].count(),
        "year_range": grp["year"].agg(lambda s: f"{s.min()}-{s.max()}"),
        "total_cells": grp["total_cells"].sum(),
        "discrepancies": grp["discrepancies"].sum(),
        "actionable_disc": grp["actionable_disc"].sum(),
        "patched": grp["patches_applied_per_csv"].apply(
            lambda s: int(s[s >= 0].sum()) if (s >= 0).any() else 0),
        "patched_years": grp["patches_applied_per_csv"].apply(
            lambda s: int((s >= 0).sum())),
    }).reset_index()

    decade_df["ocr_accuracy_pct"] = (
        1 - decade_df["discrepancies"] / decade_df["total_cells"]
    ) * 100
    decade_df["fix_pct_actionable"] = decade_df.apply(
        lambda r: (r["patched"] / r["actionable_disc"] * 100)
                  if (r["patched"] > 0 and r["actionable_disc"] > 0) else None,
        axis=1
    )

    out_csv = OUT_DIR / "extraction_accuracy_by_decade.csv"
    decade_df.to_csv(out_csv, index=False)
    print(f"Wrote {out_csv.name}")

    # --- Overall aggregate --------------------------------------------------
    total_cells = int(df["total_cells"].sum())
    total_disc  = int(df["discrepancies"].sum())
    overall_ocr = (1 - total_disc / total_cells) * 100

    patched = df[df["patches_applied_per_csv"] >= 0].copy()
    n_patched_yrs = len(patched)
    patched_actionable = int(patched["actionable_disc"].sum())
    patches_applied = int(patched["patches_applied_per_csv"].sum())
    fix_rate = (patches_applied / patched_actionable * 100
                if patched_actionable else None)

    # --- Bar chart: OCR accuracy by decade ---------------------------------
    fig, ax = plt.subplots(figsize=(8, 4.5))
    bars = ax.bar(decade_df["decade"], decade_df["ocr_accuracy_pct"],
                  color="steelblue", edgecolor="black", linewidth=0.5)
    ax.set_ylim(94, 100.2)
    ax.set_ylabel("Human OCR accuracy (% of rows matching PDF)")
    ax.set_title("NUST extraction accuracy by decade (vs source PDFs)",
                 fontsize=12)
    ax.axhline(overall_ocr, color="darkred", linestyle="--", linewidth=1,
               label=f"Overall: {overall_ocr:.2f}%")
    ax.grid(axis="y", alpha=0.3)
    for bar, pct, n in zip(bars, decade_df["ocr_accuracy_pct"], decade_df["total_cells"]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.05,
                f"{pct:.2f}%\n({n:,} rows)",
                ha="center", va="bottom", fontsize=8)
    ax.legend(loc="lower left")
    plt.tight_layout()
    png_path = OUT_DIR / "extraction_accuracy_by_decade.png"
    plt.savefig(png_path, dpi=150)
    plt.close()
    print(f"Wrote {png_path.name}")

    # --- Presentation markdown ---------------------------------------------
    md = []
    md.append("# NUST extraction accuracy — presentation summary\n")
    md.append("## Headline\n")
    md.append(f"- **{overall_ocr:.2f}% human OCR accuracy** across "
              f"{len(df)} years ({total_cells:,} rows QC'd vs source PDFs)\n")
    md.append(f"- **{total_disc:,} cell-level discrepancies** identified by Claude QC\n")
    if fix_rate is not None:
        md.append(f"- **{fix_rate:.1f}% Claude fix rate** on actionable discrepancies "
                  f"({patches_applied:,}/{patched_actionable:,} across "
                  f"{n_patched_yrs} patched years)\n\n")
    else:
        md.append("- Claude auto-patch fix rate: N/A (apply_patches logs absent; superseded by the "
                  "pre/post 'resolved-in-corpus' metric — see 09_extraction_accuracy_prepost)\n\n")

    md.append("## OCR accuracy by decade\n")
    md.append("| Decade | Years | Rows QC'd | Discrepancies | OCR accuracy |\n")
    md.append("|--------|------:|-----------:|--------------:|-------------:|\n")
    for _, r in decade_df.iterrows():
        md.append(f"| **{r['decade']}** ({r['year_range']}) "
                  f"| {int(r['years_n'])} "
                  f"| {int(r['total_cells']):,} "
                  f"| {int(r['discrepancies']):,} "
                  f"| **{r['ocr_accuracy_pct']:.2f}%** |\n")
    md.append(f"| **All** | **{len(df)}** | **{total_cells:,}** | **{total_disc:,}** "
              f"| **{overall_ocr:.2f}%** |\n\n")

    md.append("## Claude agent auto-fix rate (patched years only)\n")
    md.append("Patches are auto-applied by `fixes/apply_patches_YYYY.py` based on "
              "the QC discrepancy list, subject to per-trait thresholds.\n\n")
    md.append("| Decade | Patched yrs | Actionable disc | Patches applied | Fix rate |\n")
    md.append("|--------|------------:|----------------:|----------------:|---------:|\n")
    for _, r in decade_df.iterrows():
        if int(r["patched_years"]) == 0 or pd.isna(r["fix_pct_actionable"]):
            continue
        md.append(f"| **{r['decade']}** "
                  f"| {int(r['patched_years'])} "
                  f"| {int(r['actionable_disc']):,} "
                  f"| {int(r['patched']):,} "
                  f"| **{r['fix_pct_actionable']:.1f}%** |\n")
    md.append(f"| **All patched** | **{n_patched_yrs}** | **{patched_actionable:,}** "
              f"| **{patches_applied:,}** | **{fix_rate:.1f}%** |\n\n")

    md.append("## How accuracy is measured\n")
    md.append("1. Human OCR'd the source PDF -> xlsx\n")
    md.append("2. Claude extracted that xlsx -> `combined_YYYY_phenotypesTable.csv`\n")
    md.append("3. Claude QC (`qc_pdf_vs_csv.py --mode values`) compared every CSV "
              "cell against the same PDF; flagged discrepancies\n")
    md.append("4. `fixes/apply_patches_YYYY.py` auto-applied a subset of "
              "discrepancies to the validated CSV (subject to thresholds and "
              "SKIP_PHENOTYPES={YieldRank})\n")
    md.append("- A 'row' = one (Test, Strain, City, Phenotype) measurement "
              "in the long-format approved CSV.\n")
    md.append("5. **OCR accuracy** = (1 - discrepancies / total_rows) × 100\n")
    md.append("6. **Claude fix rate** = patches_applied / actionable_discrepancies × 100\n\n")

    md.append("## Caveats\n")
    md.append("- Accuracy is relative to the source PDF (the assumed ground truth). "
              "PDFs themselves may contain typesetting typos -- those count as OCR errors "
              "in this report.\n")
    md.append("- The 1960s era (1965-1970) has the lowest accuracy "
              "(~96-97%); these mid-century reports had severe OCR scanning "
              "limitations and explicit 'QUALITY TOO POOR' annotations in some pages.\n")
    md.append("- Late 1980s (1987-1988) reaches 99.7%+ accuracy, reflecting "
              "cleaner source typesetting.\n")
    md.append("- Fix rate >100% in some years (e.g. 1969: 102.8%) reflects that "
              "apply_patches caught extra cells beyond the QC discrepancy list "
              "via OCR variant cleanup passes.\n")

    md_path = OUT_DIR / "extraction_accuracy_presentation.md"
    md_path.write_text("".join(md), encoding="utf-8")
    print(f"Wrote {md_path.name}")

    # --- Console summary ----------------------------------------------------
    print(f"\n{'='*60}")
    print(f"NUST EXTRACTION ACCURACY — PRESENTATION SUMMARY")
    print(f"{'='*60}")
    print(f"Overall OCR accuracy:  {overall_ocr:.2f}%  ({total_cells:,} rows)")
    print(f"Claude fix rate:       {fix_rate:.1f}%  ({patches_applied:,}/{patched_actionable:,} actionable)")
    print(f"Years covered:         {len(df)} (range {df['year'].min()}-{df['year'].max()})")
    print(f"\nDecade roll-up:")
    print(decade_df[["decade", "year_range", "years_n", "total_cells",
                     "discrepancies", "ocr_accuracy_pct"]].to_string(index=False))


if __name__ == "__main__":
    main()
