#!/usr/bin/env python
"""
report_maturity_gaps.py
========================
Enumerate every (Year, Test, City) combo that still has raw Maturity
offsets in the F4U phenotypesTable1.csv (i.e. hard violations remaining
after all anchor extractions). Outputs:

  logs/NUST_maturity_gaps_summary.md
    Year-level summary + per-Test breakdown + top no-anchor cities.
  logs/NUST_maturity_gaps_detail.csv
    One row per (Year, Test, City) with offset_cells count.

Usage:
    uv run python fixes/report_maturity_gaps.py
"""
import sys
import re
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import pandas as pd

_FIXES = Path(__file__).parent
sys.path.insert(0, str(_FIXES))

from apply_patches_corpus_maturity_doy import (  # type: ignore
    find_f4u, parse_offset, is_doy, canonicalize_city,
)
from apply_patches_corpus_maturity_doy_via_ocr import (  # type: ignore
    load_anchors_from_standardized,
)

REPO_ROOT = _FIXES.parent
STD_DIR = REPO_ROOT / "analysis" / "data" / "yellow_standardized"
LOGS_DIR = REPO_ROOT / "logs"
LOGS_DIR.mkdir(exist_ok=True)


def analyze_year(year: int):
    """For one year, return (gaps_df, summary_dict). gaps_df has columns
    Year/Test/City/Offset_Cells/Anchor_Status."""
    f4u = find_f4u(year)
    if not f4u:
        return None, None
    df = pd.read_csv(f4u, dtype=str)
    if "Phenotype" not in df.columns:
        return None, None
    mat = df[df["Phenotype"] == "Maturity"].copy()
    if mat.empty:
        return None, None
    anchors, test_means = load_anchors_from_standardized(year, STD_DIR)

    # Aggregate by (Test, City)
    no_anchor: dict[tuple[str, str], int] = {}
    converted: dict[tuple[str, str], int] = {}
    for _, row in mat.iterrows():
        v = row["Value"]
        if v is None or pd.isna(v):
            continue
        sv = str(v).strip()
        if is_doy(sv):
            continue
        if parse_offset(sv) is None:
            continue
        t = str(row["Test"]).strip()
        c_raw = str(row["City"]).strip()
        c_canon = canonicalize_city(c_raw)
        key = (t, c_raw, c_canon)
        if (t, c_canon) in anchors:
            converted[key] = converted.get(key, 0) + 1
        else:
            no_anchor[key] = no_anchor.get(key, 0) + 1

    gaps_rows = []
    for (t, c_raw, c_canon), n in no_anchor.items():
        gaps_rows.append({
            "Year": year, "Test": t, "City": c_raw,
            "City_canon": c_canon, "Offset_Cells": n,
        })
    gaps_df = pd.DataFrame(gaps_rows)
    if not gaps_df.empty:
        gaps_df = gaps_df.sort_values(
            ["Year", "Test", "Offset_Cells"],
            ascending=[True, True, False]
        )

    # Summary
    n_total = len(mat)
    n_doy = sum(
        1 for v in mat["Value"]
        if v is not None and not pd.isna(v) and is_doy(str(v).strip())
    )
    n_off = sum(no_anchor.values()) + sum(converted.values())
    summary = {
        "Year": year,
        "Maturity_Total": n_total,
        "Already_DOY": n_doy,
        "Offsets_Resolvable": sum(converted.values()),
        "Offsets_NoAnchor": sum(no_anchor.values()),
        "n_NoAnchor_combos": len(no_anchor),
        "n_Tests_with_gaps": len({t for (t, _, _) in no_anchor.keys()}),
    }
    return gaps_df, summary


def categorize_year_status(summary: dict) -> str:
    """Categorize each year's data status."""
    if summary["Offsets_NoAnchor"] == 0:
        return "Complete"
    if summary["Offsets_Resolvable"] == 0:
        return "No anchor source"
    return "Partial coverage"


def main():
    print("Building Maturity gaps report...\n")
    all_gaps = []
    all_summaries = []
    for year in range(1941, 1989):
        if year == 1975:
            continue
        gaps_df, summary = analyze_year(year)
        if gaps_df is not None and not gaps_df.empty:
            all_gaps.append(gaps_df)
        if summary is not None:
            summary["Status"] = categorize_year_status(summary)
            all_summaries.append(summary)

    summary_df = pd.DataFrame(all_summaries)
    summary_df["Pct_NoAnchor"] = (
        summary_df["Offsets_NoAnchor"] / summary_df["Maturity_Total"] * 100
    ).round(1)

    detail_df = pd.concat(all_gaps, ignore_index=True) if all_gaps else pd.DataFrame()

    # Write outputs
    detail_csv = LOGS_DIR / "NUST_maturity_gaps_detail.csv"
    detail_df.to_csv(detail_csv, index=False)
    print(f"Wrote {detail_csv.name} ({len(detail_df):,} rows)")

    summary_csv = LOGS_DIR / "NUST_maturity_gaps_summary.csv"
    summary_df.to_csv(summary_csv, index=False)
    print(f"Wrote {summary_csv.name} ({len(summary_df)} years)")

    # Markdown report
    md_lines = []
    md_lines.append("# NUST Maturity DOY — Remaining Gaps Report")
    md_lines.append("")
    md_lines.append("Generated by `fixes/report_maturity_gaps.py` from the")
    md_lines.append("current F4U `phenotypesTable1.csv` files + Sojabone-")
    md_lines.append("standardized anchor xlsx files.")
    md_lines.append("")
    md_lines.append("**Note**: 1975 is excluded (already complete via separate")
    md_lines.append("PDF-direct extraction). 1989-2025 use F4U with native DOY")
    md_lines.append("values and have no hard violations.")
    md_lines.append("")
    md_lines.append("## Per-year summary")
    md_lines.append("")
    md_lines.append("Status legend:")
    md_lines.append("- **Complete**: 0 raw offsets remaining")
    md_lines.append("- **Partial coverage**: anchors exist for some (Test, City) "
                    "but not all")
    md_lines.append("- **No anchor source**: data sparsity — neither Yellow nor "
                    "Sojabone yielded usable anchors")
    md_lines.append("")
    md_lines.append("| Year | Total | DOY | Resolved | No-Anchor | Status | "
                    "Tests w/ gaps |")
    md_lines.append("|---:|---:|---:|---:|---:|:---|---:|")
    for _, r in summary_df.iterrows():
        md_lines.append(
            f"| {int(r['Year'])} | {r['Maturity_Total']:,} | "
            f"{r['Already_DOY']:,} | {r['Offsets_Resolvable']:,} | "
            f"{r['Offsets_NoAnchor']:,} ({r['Pct_NoAnchor']:.1f}%) | "
            f"{r['Status']} | {r['n_Tests_with_gaps']} |"
        )
    md_lines.append("")
    md_lines.append(f"**Total no-anchor cells: "
                    f"{summary_df['Offsets_NoAnchor'].sum():,}** across "
                    f"{len(summary_df)} years.")
    md_lines.append("")

    # Per-year breakdown: top no-anchor (Test, City) combos
    md_lines.append("## Per-year (Test, City) breakdown")
    md_lines.append("")
    md_lines.append("For each year with > 0 no-anchor cells, lists (Test, City) "
                    "combos and the cell count. The full detail is in "
                    "`NUST_maturity_gaps_detail.csv`.")
    md_lines.append("")
    for _, sr in summary_df.iterrows():
        year = int(sr["Year"])
        if sr["Offsets_NoAnchor"] == 0:
            continue
        md_lines.append(f"### {year} — {sr['Offsets_NoAnchor']:,} no-anchor "
                        f"cells across {sr['n_NoAnchor_combos']} combos")
        md_lines.append("")
        year_gaps = detail_df[detail_df["Year"] == year]
        # Group by Test
        by_test = year_gaps.groupby("Test")["Offset_Cells"].agg(
            ["sum", "count"]
        ).sort_values("sum", ascending=False)
        md_lines.append("| Test | Cities | Cells |")
        md_lines.append("|:---|---:|---:|")
        for test, row in by_test.iterrows():
            md_lines.append(f"| {test} | {int(row['count'])} | "
                            f"{int(row['sum']):,} |")
        # Top 10 cities for this year
        md_lines.append("")
        md_lines.append("Top 10 (Test, City) combos:")
        md_lines.append("")
        md_lines.append("| Test | City | Cells |")
        md_lines.append("|:---|:---|---:|")
        for _, gr in year_gaps.head(10).iterrows():
            md_lines.append(
                f"| {gr['Test']} | {gr['City']} | {int(gr['Offset_Cells'])} |"
            )
        md_lines.append("")

    md_path = LOGS_DIR / "NUST_maturity_gaps_summary.md"
    md_path.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"Wrote {md_path.name}")

    # Console summary
    print()
    print(summary_df.to_string(index=False))
    print()
    print(f"Total no-anchor cells: {summary_df['Offsets_NoAnchor'].sum():,}")
    by_status = summary_df.groupby("Status")["Offsets_NoAnchor"].sum()
    print(f"By status:")
    print(by_status.to_string())


if __name__ == "__main__":
    main()
